2 css
banan320/homeWorkPS pull request #5
Opened 2023-12-06 19:34 UTC by banan320

2023-12-07 17:53 UTC, Levitinn requested changes

2023-12-07 17:53 UTC, Levitinn commented on 2-Form/index.html
>        </section>
это не две разные секции, а одна

2023-12-07 17:53 UTC, Levitinn commented on 2-Form/index.html
>              <label for="email"></label
а почему инпуты не внутри label?

2023-12-07 18:10 UTC, banan320 commented on 2-Form/index.html
>        </section>
как показал автор, так и повторил. во всех уроках про формы было именно так. как нестранно форма работает

2023-12-07 18:11 UTC, banan320 commented on 2-Form/index.html
>              <label for="email"></label
как показал автор, так и повторял. во всех видео с формой было именно так. как нестранно форма работает.

2023-12-07 18:16 UTC, banan320 commented on 2-Form/index.html
>        </section>
Что конкретно мне нужно менять? 
Таким образом, в Интернете вы найдете HTML-страницы с <section> элементами, содержащими элементы <article>, и <article> элементы, содержащие <section> элементы.
https://html5css.ru/html/html5_semantic_elements.php

2023-12-08 18:29 UTC, Levitinn commented on 2-Form/index.html
>        </section>
ты не правильно меня понял. я сказал о том, что у тебя в макете есть одна форма. и семантически это все целиком одна секция. а ты разделил ее на две. поправь свою верстку таким образом, вся форма целиком, находилась в одном теге section

2023-12-08 18:32 UTC, Levitinn requested changes

2023-12-08 18:32 UTC, Levitinn commented on 2-Form/index.html
>              <label for="email"></label
> как показал автор, так и повторял. во всех видео с формой было именно так. как нестранно форма работает.

работать то работает. я лишь советую тебе оптимизацию твоей разметки. мы ведь здесь, для того чтобы учиться, верно? 
смотри, у тебя есть общий див, внутри него лейбл и инпут. оставить див и внутри него инпут, либо лейбл, внутри которого инпут. таким образом ты избавишься от лишнего тега

2023-12-08 18:34 UTC, banan320 commented on 2-Form/index.html
>        </section>
поправил. но все равно не понял до конца когда уместно писать section. доки пока тоже не раскрывают мне глаза. надеюсь это сейчас не критично.

2023-12-08 18:43 UTC, banan320 commented on 2-Form/index.html
>              <label for="email"></label
такой развернутый ответ меня больше устраивает)). но див в любом случае оставляю? чтобы навешивать на него разные стили для позиции и тд. автор и дивы с лейблом вставляет, как правильно то в итоге?

2023-12-10 08:56 UTC, Levitinn commented on 2-Form/index.html
>        </section>
контент на странице мы мысленно можем поделить на секции, в макете у них может отличаться:
- фон
- свой заголовок
- ключевая мысль
Если ты видишь эти явно выраженные блоки в макете, то скорее всего это секция. 
секции чаще всего стоят на одном уровне, то есть соседним тегом у секции является другая секция

2023-12-10 08:58 UTC, Levitinn commented on 2-Form/index.html
>              <label for="email"></label
да, див используется для стилизации, а лейбл для взаимодействия с инпутом. оставляй

2023-12-10 08:58 UTC, Levitinn approved these changes

2023-12-11 16:26 UTC, merged