3 flex
banan320/homeWorkPS pull request #6
Opened 2023-12-17 18:58 UTC by banan320

2023-12-19 19:00 UTC, Levitinn requested changes

2023-12-19 19:00 UTC, Levitinn commented on 1-Blog/index.html
> +          <div class="headerLogo">
это все целиком должно быть ссылкой

2023-12-19 19:00 UTC, Levitinn commented on 1-Blog/index.html
> +            <img class="magnifier" src="./img/search.svg" alt="search" />
img в нужно класть в отдельные див

2023-12-20 07:54 UTC, banan320 commented on 1-Blog/index.html
> +          <div class="headerLogo">
в последнем коммите вложил "В" в span.

2023-12-20 18:09 UTC, Levitinn approved these changes
не используй так часто тег <article>, у тебя он почти везде используется как обертка. обычный див подойдет лучше

2023-12-20 18:18 UTC, banan320 commented
> не используй так часто тег
> 
> , у тебя он почти везде используется как обертка. обычный див подойдет лучше

тут пустая строчка. какой тег, article?

2023-12-20 18:18 UTC, merged