4 final
banan320/homeWorkPS pull request #7
Opened 2024-01-30 06:13 UTC by banan320

2024-01-30 16:38 UTC, Levitinn requested changes

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/index.html
> +          <div class="header__logo">
логотип это почти всегда ссылка

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/index.html
> +              <li>Возможности</li>
элементы навигации - тоже ссылки

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/styles/header.css
> +  padding: 40px 0;
это паддинг хедера, а не навигации

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/index.html
> +            <button class="component__btn">Личный кабинет</button>
тоже лучше ссылкой

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/styles/hero.css
> +  padding-bottom: 80px;
так же, это паддинг всей секции, а не блока с элементами. а скорее даже марджин

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/index.html
> +              <img src="./img/analysis.svg" alt="" />
у картинки нет дива - обертки. а так же не заданы максимальные размеры

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/index.html
> +          <div class="analysis border_bottom">
бордер не у данного дива. а у секции, или псевдоклассом можно расположить

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/styles/page.css
> +  padding: 60px 0 0;
аналогично. паддинг у всей секции должен быть, а не у этого дива

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/styles/components.css
> +  margin-bottom: 50px;
марджин не у этого дива, это паддинг всей секции

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/index.html
> +            <div class="section__title accounting__title">
![image](https://github.com/banan320/homeWorkPS/assets/44999446/77b02bb2-4558-4b1f-98d7-529c8a95600f)
что то напутал с отступами, посмотри границы секции, и как за них выходит контент.

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/index.html
> +                  <li><p>Excel</p></li>
это не элемент списка, а его заголовок, аналогично как и у соседнего списка

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/styles/page.css
> +  padding-bottom: 80px;
паддинг секции

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/styles/page.css
> +  padding-top: 80px;
паддинг секции

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/styles/page.css
> +  margin-bottom: 80px;
марджин секции

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/index.html
> +                  <li><img src="./img/telegram.svg" alt="" />Telegram Finio</li>
не заданы максимальные размеры иконок, а так же их нужно в отдельный див

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/styles/components.css
> +  padding-bottom: 8px;
это не паддинг, отступ должен быть марджином

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/index.html
> +              <h2>Отзывы</h2>
у этого заголовка нужно убрать марджин, и добавить его обертке

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/styles/footer.css
> +  padding-bottom: 40px;
марджин, не паддинг

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/index.html
> +            <img src="./img/logo-finio.png" alt="logo" />
нужно див обертка и макс размеры

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/index.html
> +              <li>Возможности</li>
это все ссылки

2024-01-30 16:38 UTC, Levitinn commented on 3-Finio/styles/footer.css
> +  padding-top: 32px;
марджин

2024-02-01 07:33 UTC, banan320 commented on 3-Finio/index.html
> +              <h2>Отзывы</h2>
если речь о заголовке H3, то у меня везде так. только если обернуть в отдельный div??

2024-02-01 07:41 UTC, banan320 commented on 3-Finio/index.html
> +              <h2>Отзывы</h2>
пиши пожалуйста номер строчки. в редакторе комментарии съехали и я не понял сразу к какому элементу было адресованно.

2024-02-01 08:09 UTC, banan320 commented on 3-Finio/styles/footer.css
> +  padding-top: 32px;
тогда ломается полоса на бордере.

2024-02-01 08:16 UTC, banan320 commented on 3-Finio/styles/hero.css
> +  padding-bottom: 80px;
тут тоже сломается полоса на ширину контейнера. только если на всем сайте делать ее отдельным дивом и задавать максимальный размер?

2024-02-01 17:26 UTC, Levitinn requested changes

2024-02-01 17:26 UTC, Levitinn commented on 3-Finio/index.html
> +              <h2>Отзывы</h2>
комментарий всегда относится к ближайшей сверху строке.
![image](https://github.com/banan320/homeWorkPS/assets/44999446/a2368e10-7222-45bb-a9a6-c618588c5106)
ты исправил верно)

2024-02-01 17:26 UTC, Levitinn commented on 3-Finio/styles/hero.css
> +  padding-bottom: 80px;
или ты можешь сделать паддинг, но у секции, и бордеть дать ей. но тогда сломается ширина бордера, верно. 
тогда ты можешь сделать полосу псевдоклассом

2024-02-01 17:26 UTC, Levitinn commented on 3-Finio/styles/footer.css
> +  padding-top: 32px;
здесь принимается, я пропустил момент с бордером

2024-02-01 17:26 UTC, Levitinn commented on 3-Finio/styles/page.css
> +  padding-bottom: 80px;
здесь тоже. принимается

2024-02-02 07:33 UTC, banan320 commented on 3-Finio/styles/hero.css
> +  padding-bottom: 80px;
по моему получились костыли... пришлось добавить для секции маржин по бокам, чтобы во время адаптива полоса не прилипала к границе экрана. так сказать остается контейнер, но в то же время отодвинулся основной контект в этой секции.

2024-02-08 19:11 UTC, merged